# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "GHPRSummary"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod.deploy.parameters]
stack_name = "GHPRSummary"
resolve_s3 = true
s3_prefix = "GHPRSum"
region = "ap-south-1"
profile = "playground"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "Project=\"GHPRSum\" Environment=\"Prod\" RepositoryOwner=\"facebook\" Repository=\"react\""
image_repositories = []
